# Generated by Django 5.0.7 on 2024-07-22 22:13

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurrogacyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement', models.FileField(blank=True, max_length=500, null=True, upload_to=payments.models.get_file_path)),
                ('signed', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('expected_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents_plans', to=settings.AUTH_USER_MODEL)),
                ('expected_parents_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents_partners_plans', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='surrogacy_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
