# Generated by Django 5.0.7 on 2024-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_invoice_user_alter_invoice_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
