# Generated by Django 5.0.7 on 2024-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
