# Generated by Django 5.0.7 on 2024-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_invoice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
