# Generated by Django 5.0.7 on 2024-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_invoice_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
