# Generated by Django 5.1.1 on 2024-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_validatedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cart',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
