# Generated by Django 5.1.4 on 2025-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_vendorpaymentsprofile_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
