# Generated by Django 5.2 on 2025-04-27 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_invoice_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='surrogacyplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surrogacyplan',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surrogacyplan',
            name='unpaid',
            field=models.FloatField(default=0.0),
        ),
    ]
