# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.storage
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_verified', models.BooleanField(default=True)),
                ('identity_verifying', models.BooleanField(default=False)),
                ('id_valid', models.BooleanField(default=False)),
                ('identity_verification_failed', models.BooleanField(default=False)),
                ('identity_verification_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default=users.models.generate_username, max_length=20, null=True, unique=True)),
                ('preferred_name', models.CharField(blank=True, default='you', max_length=20, null=True)),
                ('image', models.ImageField(default='default.png', upload_to=users.models.get_image_path)),
                ('image_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=users.models.get_image_path)),
                ('image_public', models.ImageField(blank=True, null=True, upload_to=users.models.get_image_path)),
                ('image_public_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=users.models.get_image_path)),
                ('rotation', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('wishlist', models.TextField(blank=True, default='')),
                ('email_verified', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_messages', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribed', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('moderator', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('admin_public', models.BooleanField(default=True)),
                ('email_valid', models.BooleanField(default=True)),
                ('vendor', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=15)),
                ('language_code', models.CharField(default='', max_length=10)),
                ('ip', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('recovery_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('verification_code', models.IntegerField(blank=True, default=None, null=True)),
                ('verification_code_length', models.IntegerField(blank=True, default=6, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('enable_two_factor_authentication', models.BooleanField(default=False)),
                ('tfa_authenticated', models.BooleanField(default=False)),
                ('security_call', models.DateTimeField(default=django.utils.timezone.now)),
                ('tfa_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('tfa_code_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_send_tfa', models.DateTimeField(default=django.utils.timezone.now)),
                ('tfa_authorized_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tfa_enabled', models.BooleanField(default=False)),
                ('tfa_attempts', models.IntegerField(default=0)),
                ('can_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_face_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_scan_id', models.DateTimeField(default=django.utils.timezone.now)),
                ('timezone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('interactive', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('interactive_uuid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('identity_confirmed', models.BooleanField(default=False)),
                ('face_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('enable_facial_recognition', models.BooleanField(default=False)),
                ('enable_facial_recognition_bypass', models.BooleanField(default=True)),
                ('hide_logo', models.BooleanField(default=False)),
                ('kick', models.BooleanField(default=False)),
                ('shake_to_logout', models.BooleanField(default=False)),
                ('id_front_scanned', models.BooleanField(default=False)),
                ('id_back_scanned', models.BooleanField(default=False)),
                ('disable_id_face_match', models.BooleanField(default=False)),
                ('use_additional_mrz_security', models.BooleanField(default=False)),
                ('use_additional_nfc_security', models.BooleanField(default=False)),
                ('finished_signup', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('idscan_active', models.BooleanField(default=False)),
                ('idscan_plan', models.IntegerField(default=0)),
                ('idscan_used', models.IntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='feed.post')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
