# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations, models
import feed.storage
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_face_id_alter_profile_interactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=users.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_public',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_public_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=users.models.get_image_path),
        ),
    ]
