# Generated by Django 4.2.5 on 2023-10-04 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interactive',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interactive_uuid',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recovery_token',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=500),
        ),
    ]
