# Generated by Django 4.2.5 on 2023-10-04 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_face_id_alter_profile_interactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_like',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
