# Generated by Django 4.2.5 on 2023-10-14 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_enable_facial_recognition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_like',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
