# Generated by Django 4.2.6 on 2023-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_can_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
