# Generated by Django 4.2.6 on 2023-11-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_identity_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_biometrics',
            field=models.BooleanField(default=False),
        ),
    ]
