# Generated by Django 4.2.6 on 2023-11-21 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_profile_enable_biometrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_linked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
