# Generated by Django 4.2.6 on 2023-12-20 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_accountlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='', max_length=100)),
                ('length', models.IntegerField(default=6)),
                ('attempts', models.IntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
