# Generated by Django 5.0.3 on 2024-03-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_cover_image_profile_cover_image_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
