# Generated by Django 5.0.3 on 2024-03-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_refresh_token_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_cover_offsite',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_offsite',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_thumb_offsite',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
