# Generated by Django 5.0.3 on 2024-04-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_bash_profile_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='g251DC5X', max_length=64, null=True),
        ),
    ]
