# Generated by Django 5.0.3 on 2024-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='E9MDv1m0', max_length=64, null=True),
        ),
    ]
