# Generated by Django 5.0.3 on 2024-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='Y0i3LgLl', max_length=64, null=True),
        ),
    ]
