# Generated by Django 5.0.3 on 2024-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='CKQiUNM1', max_length=64, null=True),
        ),
    ]
