# Generated by Django 5.0.3 on 2024-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default='ff116955-ff35-4293-905c-35e675065783', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='U2eEoi08', max_length=64, null=True),
        ),
    ]
