# Generated by Django 5.0.3 on 2024-04-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_idscan_api_key_alter_profile_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='rd0avEPq', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default='d87a7c43-df25-4c29-802e-f7f1cfc527d6', max_length=36, null=True),
        ),
    ]
