# Generated by Django 5.0.3 on 2024-05-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_profile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='0Vw1SvtU', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default='725d2552-58de-4df5-a004-f39211649917', max_length=36, null=True),
        ),
    ]
