# Generated by Django 5.0.3 on 2024-05-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='dH2hV1rH', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default='166e9f48-1659-41b9-a3d5-9533e5305322', max_length=36, null=True),
        ),
    ]
