# Generated by Django 5.0.3 on 2024-05-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default='7QZSaR8I', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default='6431deb6-3b30-49ae-b5e8-0c0619a48b69', max_length=36, null=True),
        ),
    ]
