# Generated by Django 5.0.6 on 2024-05-20 00:51

import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default=users.models.get_pass_string, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idscan_api_key',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_cover_offsite',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_thumb_offsite',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
