# Generated by Django 5.0.6 on 2024-05-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_profile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_offsite',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
