# Generated by Django 5.0.6 on 2024-06-15 06:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profile_image_offsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='static/default.png', upload_to=users.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.png', upload_to=users.models.get_image_path),
        ),
    ]
