# Generated by Django 5.0.6 on 2024-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_profile_cover_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=39, null=True),
        ),
    ]
