# Generated by Django 5.1.1 on 2024-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_historicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='image_cover_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='image_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='image_thumb_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_cover_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_thumb_offsite',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
