# Generated by Django 5.1.1 on 2024-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_historicalprofile_image_cover_offsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
