# Generated by Django 5.1.3 on 2024-11-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_historicalprofile_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfatoken',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mfatoken',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
