# Generated by Django 5.1.3 on 2024-11-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_mfatoken_age_mfatoken_key_mfatoken_permitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfatoken',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='permitted',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='sex',
        ),
        migrations.AlterField(
            model_name='mfatoken',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
