# Generated by Django 5.1.4 on 2024-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_mfatoken_age_remove_mfatoken_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='enable_two_factor_authentication',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enable_two_factor_authentication',
            field=models.BooleanField(default=True),
        ),
    ]
