# Generated by Django 5.1.7 on 2025-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_historicalprofile_enable_two_factor_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='credentials',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='credentials',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
