# Generated by Django 5.2 on 2025-05-23 23:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_historicalprofile_credentials_profile_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='email_password',
            field=models.CharField(blank=True, default=users.models.get_pass_string, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_password',
            field=models.CharField(blank=True, default=users.models.get_pass_string, max_length=255, null=True),
        ),
    ]
