# Generated by Django 5.2.4 on 2025-07-21 08:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_historicalprofile_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=users.models.generate_username, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='preferred_name',
            field=models.CharField(blank=True, default='you', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default=users.models.generate_username, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, default='you', max_length=50, null=True),
        ),
    ]
