# Generated by Django 5.2.4 on 2025-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_historicalprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
