# Generated by Django 5.2.4 on 2025-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_historicalprofile_full_name_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='preferred_language',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='', max_length=10),
        ),
    ]
