# Generated by Django 5.2.4 on 2025-08-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_identifier_alter_event_end_time_and_more'),
        ('meetings', '0004_alter_meeting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.meeting'),
        ),
    ]
