# Generated by Django 5.2.8 on 2026-04-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retargeting', '0004_historicalscheduledemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscheduledemail',
            name='bcc',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='historicalscheduledemail',
            name='cc',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='bcc',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='cc',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
