selector_languages = {
    'en': 'English (Generic)',
    'en-US': 'English (US)',
    'en-UK': 'English (UK)',
    'es': 'Española',
    'fr': 'Français',
    'de': 'Deutsch',
    'nl': 'Nederlands',
    'af': 'Afrikaans',
    'ar': 'عربي',
    'pt': 'Português (Portugal, Brazil)',
    'id': 'Bahasa',
    'hi': 'हिंदी',
    'ru': 'Русский',
    'zh-CN': '中国人',
    'ja': '日本語',
    'th': 'แบบไทย',
    'tl': 'Filipino',
    'cs': 'čeština',
    'he': 'עִברִית',
    'it': 'Italiana',
    'no': 'norsk',
    'pl': 'Polski',
    'sv': 'svenska',
    'tr': 'Türkçe',
    'uk': 'українська',
    'vi': 'Tiếng Việt',
    'zu': 'Zulu',
    'sq': 'shqiptare'
}
