# Generated by Django 4.2.6 on 2023-12-09 02:57

from django.db import migrations, models
import django.db.models.deletion
import synthesizer.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=synthesizer.models.get_file_path),
        ),
        migrations.AddField(
            model_name='note',
            name='length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='project',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='volume',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='midi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='pitch',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Synth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=synthesizer.models.get_file_path)),
                ('index', models.FloatField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('gain', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('distortion', models.IntegerField(default=0)),
                ('highpass_filter', models.IntegerField(default=0)),
                ('lowpass_filter', models.IntegerField(default=0)),
                ('compressor', models.IntegerField(default=0)),
                ('delay', models.IntegerField(default=0)),
                ('reverb', models.IntegerField(default=0)),
                ('pitch_adjust', models.IntegerField(default=0)),
                ('fade', models.IntegerField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('instrument', models.IntegerField(default=0)),
                ('continuous_pitch', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synths', to='synthesizer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track', models.IntegerField(default=0)),
                ('index', models.FloatField(default=0)),
                ('length', models.IntegerField(default=4)),
                ('midi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='synthesizer.midi')),
            ],
        ),
    ]
