# Generated by Django 4.2.6 on 2023-12-09 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizer', '0002_midi_file_note_length_project_bpm_project_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
