# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(default='en', max_length=10)),
                ('dest', models.CharField(default='en', max_length=10)),
                ('src_content', models.TextField(default='')),
                ('dest_content', models.TextField(default='')),
                ('pronunciation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
