# Generated by Django 5.2.4 on 2025-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_cachedtranslation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedtranslation',
            name='src_hash',
            field=models.IntegerField(default=0),
        ),
    ]
