# Generated by Django 5.2.4 on 2025-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_cachedtranslation_src_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedtranslation',
            name='src_hash',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
