# Generated by Django 4.2.5 on 2023-10-04 16:02

import audio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_file', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.FileField(blank=True, null=True, upload_to=audio.models.get_file_path)),
                ('content_backup', models.FileField(blank=True, null=True, upload_to=audio.models.get_file_path)),
                ('plot', models.ImageField(blank=True, null=True, upload_to=audio.models.get_file_path)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('transcript', models.TextField(blank=True, default='', null=True)),
                ('public', models.BooleanField(default=False)),
                ('confirmation_id', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
