# Generated by Django 5.0.1 on 2024-03-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='pitches',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='volumes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
