# Generated by Django 5.0.1 on 2024-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audiorecording_pitch_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='session',
            field=models.CharField(default='', max_length=32),
        ),
    ]
