# Generated by Django 5.0.3 on 2024-04-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audiorecording_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='fingerprint',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
