# Generated by Django 5.0.6 on 2024-05-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_audiorecording_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
