# Generated by Django 5.2.6 on 2025-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_chatmessage_vendor_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
