# Generated by Django 5.2.8 on 2025-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_chatmessage_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
