# Generated by Django 5.0.7 on 2024-08-09 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('permitted', models.BooleanField(default=True)),
            ],
        ),
    ]
