# Generated by Django 5.0.7 on 2024-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='key',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
