# Generated by Django 5.0.7 on 2024-08-15 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_key_age_key_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
