# Generated by Django 5.0.7 on 2024-09-04 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_key_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='keyed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
