# Generated by Django 5.2.8 on 2025-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
