# Generated by Django 4.2.5 on 2023-10-04 16:02

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields
import verify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('document', models.ImageField(null=True, upload_to=verify.models.get_document_path)),
                ('document_back', models.ImageField(null=True, upload_to=verify.models.get_document_path)),
                ('signature', jsignature.fields.JSignatureField(null=True)),
                ('document_number', models.TextField(blank=True, default='', null=True)),
                ('document_ocr', models.TextField(blank=True, default='', null=True)),
                ('barcode_data', models.TextField(blank=True, default='', null=True)),
                ('barcode_data_processed', models.TextField(blank=True, default='', null=True)),
                ('idscan', models.TextField(blank=True, default='', null=True)),
                ('idscan_text', models.TextField(blank=True, default='', null=True)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
