# Generated by Django 5.0.6 on 2024-07-06 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
        ('face', '0003_facetoken'),
        ('verify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeriFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('next', models.CharField(blank=True, default=uuid.uuid4, max_length=300, null=True)),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='face.face')),
                ('scans', models.ManyToManyField(to='barcode.documentscan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veriflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
