# Generated by Django 5.0.7 on 2024-08-16 02:29

import verify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_identitydocument_document_back_isolated'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='document_isolated',
            field=models.ImageField(null=True, upload_to=verify.models.get_document_path),
        ),
    ]
