# Generated by Django 5.2.3 on 2025-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_identitydocument_document_isolated'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='subjective',
            field=models.BooleanField(default=False),
        ),
    ]
