# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.storage
import live.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation_id', models.TextField(blank=True, default='', null=True)),
                ('frame', models.FileField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('still', models.ImageField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('still_bucket', models.FileField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=live.models.get_file_path)),
                ('still_thumbnail', models.ImageField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('still_thumbnail_bucket', models.FileField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=live.models.get_file_path)),
                ('time_captured', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('compressed', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('pitch_adjust', models.IntegerField(default=0)),
                ('safe', models.BooleanField(default=True)),
                ('difference', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_frames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('file_processed', models.FileField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=live.models.get_file_path)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('camera', models.CharField(default='private', max_length=100)),
                ('last_frame', models.DateTimeField(default=django.utils.timezone.now)),
                ('compressed', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('processing', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('interactive', models.CharField(blank=True, default='', max_length=100)),
                ('transcript', models.TextField(blank=True, default='')),
                ('safe', models.BooleanField(default=False)),
                ('frames', models.ManyToManyField(blank=True, to='live.videoframe')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_recordings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='private', max_length=100, null=True)),
                ('frame', models.FileField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('stream', models.FileField(blank=True, default=live.models.get_stream_path, null=True, upload_to=live.models.get_file_path)),
                ('still', models.ImageField(blank=True, null=True, upload_to=live.models.get_file_path)),
                ('width', models.CharField(default='1920', max_length=10)),
                ('last_frame', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('echo_cancellation', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('live', models.BooleanField(default=True)),
                ('recording', models.BooleanField(default=False)),
                ('use_websocket', models.BooleanField(default=False)),
                ('key', models.TextField(blank=True, default='')),
                ('frame_count', models.IntegerField(default=0)),
                ('confirmation_id', models.TextField(blank=True, default='', null=True)),
                ('frames', models.ManyToManyField(blank=True, related_name='camera', to='live.videoframe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_camera', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_shows', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(blank=True, default='', null=True)),
                ('thumbnail', models.TextField(blank=True, default='', null=True)),
                ('last_frame', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
