# Generated by Django 4.2.6 on 2023-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='compress_video',
            field=models.BooleanField(default=False),
        ),
    ]
