# Generated by Django 5.0.1 on 2024-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_videoframe_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='mime',
            field=models.CharField(default='mp4', max_length=10),
        ),
    ]
