# Generated by Django 5.0.1 on 2024-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_videocamera_default_videocamera_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='description',
            field=models.CharField(default='Femme Babe is live at lotteh.com', max_length=1000),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='tags',
            field=models.CharField(default='technology,software,web development,machine learning,artificial intelligence,beauty,fashion,makeup,model,celebrity', max_length=500),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='title',
            field=models.CharField(default='Femme Babe', max_length=200),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
