# Generated by Django 5.0.6 on 2024-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_videocamera_description_videocamera_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
