# Generated by Django 5.0.7 on 2024-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_videocamera_muted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='description',
            field=models.CharField(default='Lotte Harper is live at lotteh.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videocamera',
            name='title',
            field=models.CharField(default='Lotte Harper', max_length=200),
        ),
    ]
