# Generated by Django 5.1.7 on 2025-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_alter_videocamera_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocamera',
            old_name='default',
            new_name='adjust_pitch',
        ),
        migrations.AddField(
            model_name='videocamera',
            name='animate_video',
            field=models.BooleanField(default=False),
        ),
    ]
