# Generated by Django 5.1.7 on 2025-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_videoframe_adjust_pitch_videoframe_animate_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecording',
            name='frames',
            field=models.ManyToManyField(blank=True, related_name='recording', to='live.videoframe'),
        ),
    ]
