# Generated by Django 5.1.7 on 2025-03-22 11:44

import feed.storage
import live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_alter_videorecording_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='thumbnail_bucket',
            field=models.FileField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=live.models.get_still_path),
        ),
    ]
