# Generated by Django 5.1.7 on 2025-04-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0012_alter_videocamera_use_websocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='short_mode',
            field=models.BooleanField(default=False),
        ),
    ]
