# Generated by Django 5.2 on 2025-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0014_remove_videocamera_stream_videocamera_embed_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='privacy_status',
            field=models.CharField(default='public', max_length=30),
        ),
    ]
