# Generated by Django 5.2 on 2025-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0015_videocamera_privacy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocamera',
            name='livestream',
        ),
        migrations.AddField(
            model_name='videorecording',
            name='camera_id',
            field=models.CharField(blank=True, default='', max_length=21, null=True),
        ),
    ]
