# Generated by Django 5.2 on 2025-05-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0016_remove_videocamera_livestream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='bucket',
            field=models.BooleanField(default=False),
        ),
    ]
