# Generated by Django 5.2.1 on 2025-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0017_videocamera_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='tags',
            field=models.CharField(default='passive income,technology,software,web development,web apps,programming,coding,casual gaming,online business,online shopping,stream,streaming,video chat,photography,machine learning,artificial intelligence,computer vision,cryptocurrency,payments,beauty,fashion,makeup,cosmetics,esthetics,esthetician,code,coding,coder,program,programming,meme,live,egirl,django,python,webapp,website,app,google,google pixel,webrtc,chat,payment processing,model,celebrity,engineer', max_length=500),
        ),
    ]
