# Generated by Django 5.2.1 on 2025-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0018_alter_videocamera_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='microphone',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
