# Generated by Django 5.2.1 on 2025-06-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0019_videocamera_microphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='category',
            field=models.CharField(default='22', max_length=5),
        ),
    ]
