# Generated by Django 5.2.1 on 2025-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0020_videocamera_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='speech_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoframe',
            name='contains_speech',
            field=models.BooleanField(default=False),
        ),
    ]
