# Generated by Django 5.2.1 on 2025-06-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0021_videocamera_speech_only_videoframe_contains_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='vad_mode',
            field=models.CharField(default='2', max_length=1),
        ),
    ]
