# Generated by Django 5.2.3 on 2025-07-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0022_videocamera_vad_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
