# Generated by Django 5.2.3 on 2025-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0023_videorecording_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='youtube_embed',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
