# Generated by Django 5.2.3 on 2025-07-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0024_videorecording_youtube_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='video_length_minutes',
            field=models.FloatField(default=15),
        ),
    ]
