# Generated by Django 5.2.3 on 2025-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0025_videocamera_video_length_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='censor_video',
            field=models.BooleanField(default=False),
        ),
    ]
