# Generated by Django 5.2.4 on 2025-07-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0026_videocamera_censor_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
