# Generated by Django 5.2.4 on 2025-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0027_videocamera_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='framerate',
            field=models.IntegerField(default=30),
        ),
    ]
