# Generated by Django 5.2.4 on 2025-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0028_videocamera_framerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='description',
            field=models.CharField(default='Lotte Harper is live at lotteh.com', max_length=2000),
        ),
    ]
