# Generated by Django 5.2.4 on 2025-07-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0029_alter_videocamera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
