# Generated by Django 5.2.4 on 2025-07-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0030_videorecording_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='category',
            field=models.CharField(default='22', max_length=5),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
