# Generated by Django 5.2.4 on 2025-08-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0031_videorecording_category_videorecording_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='mirror',
            field=models.BooleanField(default=False),
        ),
    ]
