# Generated by Django 5.2.4 on 2025-08-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0032_videocamera_mirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='prompt',
            field=models.CharField(blank=True, default="what's in this image?", max_length=9001, null=True),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='prompt',
            field=models.CharField(blank=True, default="what's in this image?", max_length=9001, null=True),
        ),
    ]
