# Generated by Django 5.2.4 on 2025-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0033_videocamera_prompt_videorecording_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='censor_audio',
            field=models.BooleanField(default=False),
        ),
    ]
