# Generated by Django 5.2.4 on 2025-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0035_alter_videocamera_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='width',
            field=models.CharField(default='1920', max_length=100),
        ),
    ]
