# Generated by Django 5.2.4 on 2025-08-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0037_alter_videocamera_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='rotation',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
