# Generated by Django 5.2.4 on 2025-08-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0038_videocamera_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='tags_overflow',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='videocamera',
            name='tags',
            field=models.CharField(default='passive income,technology,software,web development,web apps,programming,coding,casual gaming,online business,online shopping,stream,streaming,video chat,photography,machine learning,artificial intelligence,computer vision,cryptocurrency,payments,beauty,fashion,makeup,cosmetics,esthetics,esthetician,code,coding,coder,program,programming,meme,live,egirl,django,python,webapp,website,app,google,google pixel,webrtc,chat,payment processing,model,celebrity,engineer', max_length=1000),
        ),
    ]
