# Generated by Django 5.2.4 on 2025-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0039_videocamera_tags_overflow_alter_videocamera_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='tags',
            field=models.CharField(default='technology,software,web development,web apps,programming,coding,art,casual gaming,online business,celebrity,stream,streaming,photography,machine learning,artificial intelligence,computer vision,seattle,cryptocurrency,payments,beauty,fashion,makeup,cosmetics,lifestyle,health,fitness,games,music,podcast,entertainment,vlog,funny,esthetics,esthetician,code,program,viral,video,youtuber,egirl,django,python,webapp,website,app,webcam,google pixel,webrtc,chat,model,engineer', max_length=1000),
        ),
    ]
