# Generated by Django 5.2.5 on 2025-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0040_alter_videocamera_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='upload_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='upload_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
