# Generated by Django 5.2.5 on 2025-09-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0041_videocamera_upload_email_videorecording_upload_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='upload_playlist',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
