# Generated by Django 5.2.5 on 2025-09-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0042_videocamera_upload_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='upload_playlist',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
