# Generated by Django 5.2.5 on 2025-09-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0043_videorecording_upload_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='youtube_processed',
            field=models.BooleanField(default=False),
        ),
    ]
