# Generated by Django 5.2.5 on 2025-09-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0044_videorecording_youtube_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='upload_processed',
            field=models.BooleanField(default=False),
        ),
    ]
