# Generated by Django 5.2.5 on 2025-09-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0045_videorecording_upload_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecording',
            name='upload_processed',
        ),
    ]
