# Generated by Django 5.2.5 on 2025-09-14 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0046_remove_videorecording_upload_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('youtube_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
