# Generated by Django 5.2.5 on 2025-09-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0047_userplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='process_check_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
