# Generated by Django 5.2.6 on 2025-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0048_videorecording_process_check_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocamera',
            name='description',
            field=models.CharField(default='Lotte Harper is online and recording.\r\nWatch the livestream online at https://lotteh.com/stream/Daisy/\r\nMy name is Charlotte Harper, and I am a full stack Linux website and web app developer, actress, model, mother and cosmetics enthusiast living in Seattle, WA. \r\nVisit online at https://lotteh.com and glamgirlx.com\r\nChat with me at https://glamgirlx.com/chat\r\nContact me at https://glamgirlx.com/contact\r\nSee you there xoxo <3', max_length=2000),
        ),
    ]
