# Generated by Django 5.2.6 on 2025-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0049_alter_videocamera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='broadcast_youtube',
            field=models.BooleanField(default=False),
        ),
    ]
