# Generated by Django 5.2.6 on 2025-10-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0051_alter_videocamera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='server_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
