# Generated by Django 5.2.6 on 2025-10-08 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0052_videocamera_server_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPodcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transistorfm_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('explicit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transistorfm_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
