# Generated by Django 5.2.6 on 2025-10-08 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0053_userpodcast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='podcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='podcast_show_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='UserPodcastAudioUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transistorfm_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('upload_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('audio_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transistorfm_episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
