# Generated by Django 5.2.6 on 2025-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0054_videocamera_podcast_videocamera_podcast_show_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpodcastaudioupload',
            name='upload_url',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
