# Generated by Django 5.2.6 on 2025-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0055_alter_userpodcastaudioupload_upload_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpodcastaudioupload',
            name='success_json',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
