# Generated by Django 5.2.6 on 2025-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0056_userpodcastaudioupload_success_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocamera',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='videocamera',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='videocamera',
            name='still',
        ),
        migrations.AddField(
            model_name='videorecording',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='podcast',
            field=models.BooleanField(default=False),
        ),
    ]
