# Generated by Django 5.2.6 on 2025-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0057_remove_videocamera_frame_remove_videocamera_frames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
