# Generated by Django 5.2.6 on 2025-11-02 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0058_alter_videoframe_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='last_updated_playlists',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
