# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import security.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(default='', max_length=15)),
                ('session_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_agent', models.CharField(default='', max_length=200)),
                ('bypass', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIpAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('session_key', models.CharField(default='', max_length=100)),
                ('timezone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('risk_detected', models.BooleanField(default=False)),
                ('risk_recheck', models.BooleanField(default=False)),
                ('fraudguard_data', models.TextField(blank=True, default='')),
                ('page_loads', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(default='', max_length=15)),
                ('uuid_key', models.CharField(default='', max_length=36, null=True)),
                ('http_referrer', models.CharField(default='', max_length=100, null=True)),
                ('content_length', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('path', models.CharField(default='', max_length=100)),
                ('querystring', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('injection', models.TextField(default='', null=True)),
                ('injection_key', models.CharField(default='', max_length=36)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default='', max_length=100)),
                ('profile_call', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin_entered', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin_entered_incorrectly', models.DateTimeField(default=django.utils.timezone.now)),
                ('incorrect_pin_attempts', models.IntegerField(default=0)),
                ('pincode', models.TextField(default='')),
                ('ip_addresses', models.ManyToManyField(blank=True, related_name='ip_addresses', to='security.useripaddress')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(default='', max_length=100)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFCScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nfc_data_read', models.TextField(blank=True, default='')),
                ('nfc_data_written', models.TextField(blank=True, default='')),
                ('nfc_id', models.TextField(blank=True, default='')),
                ('nfc_name', models.TextField(blank=True, default='')),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MRZScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=security.models.get_document_path)),
                ('barcode_data', models.TextField(blank=True, default='')),
                ('ocr_data', models.TextField(blank=True, default='')),
                ('ocr_key', models.TextField(blank=True, default='')),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrz_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
