# Generated by Django 4.2.5 on 2023-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content_length',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='http_referrer',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='session',
            name='querystring',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(default='', max_length=500),
        ),
    ]
