# Generated by Django 4.2.5 on 2023-10-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_session_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
