# Generated by Django 4.2.5 on 2023-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_session_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content_length',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='http_referrer',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='path',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='session',
            name='querystring',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
