# Generated by Django 4.2.6 on 2023-11-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_session_content_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
