# Generated by Django 4.2.6 on 2023-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_securityprofile_biometrics_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content_length',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='http_referrer',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='querystring',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useripaddress',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useripaddress',
            name='session_key',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='useripaddress',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
