# Generated by Django 5.0.1 on 2024-03-07 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_alter_session_content_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_count', models.IntegerField(default=0)),
                ('bin_id', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('transports', models.TextField(default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
