# Generated by Django 5.0.1 on 2024-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='injected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='past_injections',
            field=models.TextField(default='', null=True),
        ),
    ]
