# Generated by Django 5.0.3 on 2024-04-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_session_injected_session_past_injections'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
