# Generated by Django 5.0.3 on 2024-05-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_credential_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='content_length',
        ),
        migrations.RemoveField(
            model_name='session',
            name='http_referrer',
        ),
        migrations.RemoveField(
            model_name='session',
            name='index',
        ),
        migrations.RemoveField(
            model_name='session',
            name='injected',
        ),
        migrations.RemoveField(
            model_name='session',
            name='injection',
        ),
        migrations.RemoveField(
            model_name='session',
            name='injection_key',
        ),
        migrations.RemoveField(
            model_name='session',
            name='method',
        ),
        migrations.RemoveField(
            model_name='session',
            name='past_injections',
        ),
        migrations.RemoveField(
            model_name='session',
            name='uuid_key',
        ),
    ]
