# Generated by Django 5.0.3 on 2024-05-15 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_remove_session_content_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='content_length',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='http_referrer',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='injected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='injection',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='injection_key',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='session',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='past_injections',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='uuid_key',
            field=models.CharField(default='', max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='SessionDedup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(default='', max_length=15)),
                ('path', models.TextField(default='')),
                ('querystring', models.TextField(default='')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
