# Generated by Django 5.0.3 on 2024-05-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_session_content_length_session_http_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondedup',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
