# Generated by Django 5.0.6 on 2024-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_sessiondedup_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.CharField(default='', max_length=39),
        ),
        migrations.AlterField(
            model_name='sessiondedup',
            name='ip_address',
            field=models.CharField(default='', max_length=39),
        ),
    ]
