# Generated by Django 5.0.6 on 2024-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_alter_session_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripaddress',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=39, null=True),
        ),
    ]
