# Generated by Django 5.0.7 on 2024-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_alter_useripaddress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
