# Generated by Django 5.0.7 on 2024-09-01 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_historicalbiometric_historicalcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseripaddress',
            name='last_updated_sun',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaluseripaddress',
            name='sunrise',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaluseripaddress',
            name='sunset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='last_updated_sun',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='sunrise',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='sunset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
