# Generated by Django 5.1.3 on 2024-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0027_historicalvivokeyscan_decoded_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnfcscan',
            name='nfc_data_read',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalnfcscan',
            name='nfc_data_written',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalnfcscan',
            name='nfc_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalnfcscan',
            name='nfc_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvivokeyscan',
            name='nfc_data_read',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvivokeyscan',
            name='nfc_data_written',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvivokeyscan',
            name='nfc_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvivokeyscan',
            name='nfc_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='nfcscan',
            name='nfc_data_read',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='nfcscan',
            name='nfc_data_written',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='nfcscan',
            name='nfc_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='nfcscan',
            name='nfc_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vivokeyscan',
            name='nfc_data_read',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vivokeyscan',
            name='nfc_data_written',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vivokeyscan',
            name='nfc_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vivokeyscan',
            name='nfc_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
