# Generated by Django 5.1.4 on 2025-02-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0029_alter_historicalsecurityprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='content_length',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='content_length',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
    ]
