# Generated by Django 5.2.4 on 2025-07-22 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0030_alter_historicalsession_content_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersession',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalusersession',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersession',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
