# Generated by Django 5.2.4 on 2025-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0031_historicalusersession_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersession',
            name='deauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='deauth',
            field=models.BooleanField(default=False),
        ),
    ]
