# Generated by Django 5.2.6 on 2025-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0032_historicalusersession_deauth_usersession_deauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersession',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalusersession',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalusersession',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
