# Generated by Django 5.2.6 on 2025-09-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0033_historicalusersession_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersession',
            name='ip_address',
            field=models.CharField(default='', max_length=39),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.CharField(default='', max_length=39),
        ),
    ]
