# Generated by Django 5.2.6 on 2025-10-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0036_alter_useripaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersession',
            name='expiry_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expiry_warning',
            field=models.BooleanField(default=False),
        ),
    ]
