# Generated by Django 5.2.8 on 2025-11-20 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0037_historicalusersession_expiry_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseripaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
