# Generated by Django 5.2.8 on 2026-04-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0038_historicaluseripaddress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsession',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
    ]
