# Generated by Django 5.2.8 on 2026-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0039_historicalsession_session_key_session_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsession',
            name='user_agent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.TextField(default=''),
        ),
    ]
