# Generated by Django 5.0.7 on 2024-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelllogin',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=39, null=True),
        ),
    ]
