# Generated by Django 5.1.6 on 2025-02-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0003_historicalshelllogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshelllogin',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='shelllogin',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
