# Generated by Django 5.2.6 on 2025-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0004_historicalshelllogin_code_shelllogin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshelllogin',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshelllogin',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalshelllogin',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shelllogin',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shelllogin',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shelllogin',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
