# Generated by Django 4.2.5 on 2023-10-04 16:02

import birthcontrol.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthControlProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_control', models.ImageField(blank=True, null=True, upload_to=birthcontrol.models.get_image_path)),
                ('birth_control_current', models.ImageField(blank=True, null=True, upload_to=birthcontrol.models.get_image_path)),
                ('birth_control_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_control_barcodes', models.TextField(blank=True)),
                ('period_start', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('reminders', models.IntegerField(default=0)),
                ('reminder_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_pill_reminder', models.BooleanField(default=True)),
                ('send_sleep_reminder', models.BooleanField(default=True)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthcontrol_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthControlPill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('notes_save', models.TextField(blank=True)),
                ('time_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminders', models.IntegerField(default=0)),
                ('taken_with_food', models.BooleanField(default=True)),
                ('flow', models.BooleanField(default=False)),
                ('intercourse', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
