# Generated by Django 5.0.3 on 2024-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcontrolpill',
            name='incontinence',
            field=models.BooleanField(default=False),
        ),
    ]
