# Generated by Django 5.1.7 on 2025-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcontrol', '0003_birthcontrolpill_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcontrolprofile',
            name='send_pill_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='birthcontrolprofile',
            name='send_sleep_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
