# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.models
import feed.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed', models.CharField(default='private', max_length=100)),
                ('uuid', models.TextField(default=uuid.uuid4, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_hash', models.TextField(blank=True)),
                ('image_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path)),
                ('image_original', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_original_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path)),
                ('image_censored', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_censored_bucket', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_censored_thumbnail', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_censored_thumbnail_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path)),
                ('image_public', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_public_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path)),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to=feed.models.get_image_path)),
                ('image_thumbnail_bucket', models.ImageField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path)),
                ('image_static', models.CharField(blank=True, max_length=100, null=True)),
                ('image_sightengine', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=feed.models.get_file_path)),
                ('file_bucket', models.FileField(blank=True, null=True, upload_to=feed.models.get_file_path)),
                ('file_sightengine', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('rotation', models.IntegerField(default=0)),
                ('enhanced', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('confirmation_id', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_recipient', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, related_name='post_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
