# Generated by Django 4.2.5 on 2023-10-04 16:37

from django.db import migrations, models
import feed.models
import feed.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed',
            field=models.CharField(default='private', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_censored',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_censored_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_censored_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_censored_thumbnail_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_original',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_original_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_public',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_public_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_static',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail_bucket',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=feed.storage.MediaStorage(), upload_to=feed.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.TextField(default=uuid.uuid4, max_length=255),
        ),
    ]
