# Generated by Django 4.2.6 on 2023-12-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secure',
            field=models.BooleanField(default=False),
        ),
    ]
