# Generated by Django 5.0.3 on 2024-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_offsite',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumb_offsite',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='offsite',
            field=models.BooleanField(default=False),
        ),
    ]
