# Generated by Django 5.0.7 on 2024-07-22 06:18

import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_post_image_offsite_post_image_thumb_offsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_censored_bucket',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=feed.storage.MediaStorage()),
        ),
    ]
