# Generated by Django 5.0.7 on 2024-07-22 06:20

import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_post_image_censored_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_censored_bucket',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=feed.storage.MediaStorage(), upload_to=''),
        ),
    ]
