# Generated by Django 5.0.7 on 2024-07-23 07:45

import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_post_image_censored_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_bucket',
            field=models.FileField(blank=True, max_length=500, null=True, storage=feed.storage.MediaStorage(), upload_to=''),
        ),
    ]
