# Generated by Django 5.0.7 on 2024-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_post_file_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
