# Generated by Django 5.0.7 on 2024-07-25 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_post_friendly_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paid_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='paid_users',
            field=models.ManyToManyField(blank=True, related_name='paid_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
