# Generated by Django 5.0.7 on 2024-07-25 08:18

import feed.models
import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_post_paid_file_post_paid_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_sample',
            field=models.FileField(blank=True, null=True, upload_to=feed.models.get_file_path),
        ),
        migrations.AddField(
            model_name='post',
            name='file_sample_bucket',
            field=models.FileField(blank=True, max_length=500, null=True, storage=feed.storage.MediaStorage(), upload_to=''),
        ),
    ]
