# Generated by Django 5.0.7 on 2024-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_post_file_sample_post_file_sample_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_compiled',
            field=models.TextField(blank=True),
        ),
    ]
