# Generated by Django 5.0.7 on 2024-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_post_date_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=10),
        ),
    ]
