# Generated by Django 5.0.7 on 2024-08-20 23:06

import django.db.models.deletion
import django.utils.timezone
import feed.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_alter_bid_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('feed', models.CharField(default='private', max_length=500)),
                ('uuid', models.TextField(default=uuid.uuid4, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('content_compiled', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('image_hash', models.TextField(blank=True)),
                ('image_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_original', models.TextField(blank=True, max_length=500, null=True)),
                ('image_original_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_censored', models.TextField(blank=True, max_length=500, null=True)),
                ('image_censored_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_censored_thumbnail', models.TextField(blank=True, max_length=500, null=True)),
                ('image_censored_thumbnail_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_public', models.TextField(blank=True, max_length=500, null=True)),
                ('image_public_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_thumbnail', models.TextField(blank=True, max_length=500, null=True)),
                ('image_thumbnail_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('image_static', models.CharField(blank=True, max_length=500, null=True)),
                ('image_sightengine', models.TextField(blank=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('file_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('file_sample', models.TextField(blank=True, max_length=100, null=True)),
                ('file_sample_bucket', models.TextField(blank=True, max_length=500, null=True)),
                ('file_sightengine', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('rotation', models.IntegerField(default=0)),
                ('price', models.CharField(default='5', max_length=10)),
                ('enhanced', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('secure', models.BooleanField(default=False)),
                ('offsite', models.BooleanField(default=False)),
                ('image_offsite', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('image_thumb_offsite', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('confirmation_id', models.TextField(blank=True)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('date_auction', models.DateTimeField(default=feed.models.get_auction_end)),
                ('paid_file', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical post',
                'verbose_name_plural': 'historical posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
