# Generated by Django 5.1.4 on 2025-01-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_historicalpost_safe_post_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='auction_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='auction_message',
            field=models.TextField(blank=True),
        ),
    ]
