# Generated by Django 5.2.6 on 2025-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_historicalpost_auction_message_post_auction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
