# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default=None, null=True, storage=face.models.FaceStorage(), upload_to=face.models.get_face_path)),
                ('hash', models.TextField(blank=True, null=True)),
                ('auth_url', models.TextField(blank=True, default='')),
                ('token', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('authorized', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
