# Generated by Django 4.2.6 on 2024-01-01 03:19

from django.db import migrations, models
import face.models
import feed.storage


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='face',
            name='image_bucket',
            field=models.ImageField(blank=True, default=None, null=True, storage=feed.storage.MediaStorage(), upload_to=face.models.get_face_path),
        ),
    ]
