# Generated by Django 5.0.1 on 2024-01-18 19:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_face_authentic_face_image_bucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='', max_length=100)),
                ('length', models.IntegerField(default=6)),
                ('attempts', models.IntegerField(default=0)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
