# Generated by Django 4.2.5 on 2023-10-04 16:02

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_onboarded', models.BooleanField(default=False)),
                ('pronouns', models.CharField(default='They', max_length=50)),
                ('subscription_fee', models.CharField(blank=True, default='50', max_length=50, null=True)),
                ('photo_tip', models.CharField(blank=True, default='5', max_length=10, null=True)),
                ('compress_video', models.BooleanField(default=False)),
                ('payout_currency', models.CharField(blank=True, default='BTC', max_length=10, null=True)),
                ('payout_address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('pitch_adjust', models.IntegerField(default=0)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='vendor_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
