# Generated by Django 4.2.6 on 2023-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='activate_surrogacy',
            field=models.BooleanField(default=False),
        ),
    ]
