# Generated by Django 4.2.6 on 2023-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorprofile_activate_surrogacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='free_trial',
            field=models.CharField(blank=True, default='30', max_length=10, null=True),
        ),
    ]
