# Generated by Django 5.0.1 on 2024-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorprofile_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='pornhub_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
