# Generated by Django 5.0.1 on 2024-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorprofile_pornhub_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='onlyfans_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
