# Generated by Django 5.0.1 on 2024-03-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorprofile_onlyfans_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
