# Generated by Django 5.0.7 on 2024-08-20 23:06

import address.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('vendors', '0006_vendorprofile_insurance_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendorProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_onboarded', models.BooleanField(default=False)),
                ('pronouns', models.CharField(default='They', max_length=50)),
                ('pornhub_link', models.CharField(default='', max_length=500)),
                ('onlyfans_link', models.CharField(default='', max_length=500)),
                ('subscription_fee', models.CharField(blank=True, default='50', max_length=50, null=True)),
                ('photo_tip', models.CharField(blank=True, default='5', max_length=10, null=True)),
                ('free_trial', models.CharField(blank=True, default='30', max_length=10, null=True)),
                ('compress_video', models.BooleanField(default=False)),
                ('activate_surrogacy', models.BooleanField(default=False)),
                ('payout_currency', models.CharField(blank=True, default='BTC', max_length=10, null=True)),
                ('payout_address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('pitch_adjust', models.IntegerField(default=0)),
                ('insurance_provider', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', address.models.AddressField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='address.address')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vendor profile',
                'verbose_name_plural': 'historical vendor profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
