# Generated by Django 5.0.7 on 2024-08-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_historicalvendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='hide_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='hide_profile',
            field=models.BooleanField(default=False),
        ),
    ]
