# Generated by Django 5.1.3 on 2024-12-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_rename_onlyfans_link_historicalvendorprofile_content_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='imgur_refresh',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='imgur_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='imgur_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='imgur_refresh',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='imgur_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='imgur_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
