# Generated by Django 5.1.3 on 2024-12-01 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_historicalvendorprofile_imgur_refresh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='imgur_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='imgur_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
