# Generated by Django 5.1.7 on 2025-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_historicalvendorprofile_logo_vendorprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='avalanche_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='polygon_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='solana_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='stellarlumens_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='usdcoin_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='avalanche_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='polygon_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='solana_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='stellarlumens_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='usdcoin_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
