# Generated by Django 5.1.7 on 2025-04-09 06:39

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_historicalvendorprofile_avalanche_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='video_intro_font',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='video_intro_text',
            field=models.CharField(default='Lotte Harper', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_intro_font',
            field=models.ImageField(default='', null=True, upload_to=vendors.models.get_font_path),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_intro_text',
            field=models.CharField(default='Lotte Harper', max_length=50),
        ),
    ]
