# Generated by Django 5.1.7 on 2025-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_historicalvendorprofile_video_intro_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='video_intro_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_intro_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
