# Generated by Django 5.1.7 on 2025-04-09 10:10

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_historicalvendorprofile_video_intro_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorprofile',
            name='video_intro_font',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='video_intro_font',
            field=models.ImageField(blank=True, default='', null=True, upload_to=vendors.models.get_font_path),
        ),
    ]
