# Generated by Django 5.2 on 2025-04-13 09:19

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_alter_historicalvendorprofile_video_intro_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='video_intro_font',
            field=models.FileField(blank=True, default='', null=True, upload_to=vendors.models.get_font_path),
        ),
    ]
