# Generated by Django 5.2 on 2025-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_alter_vendorprofile_video_intro_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='video_embed',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='video_playlist_embed',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_embed',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='video_playlist_embed',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
