# Generated by Django 5.2 on 2025-04-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_historicalvendorprofile_video_embed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvendorprofile',
            old_name='video_playlist_embed',
            new_name='playlist_embed',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='video_playlist_embed',
            new_name='playlist_embed',
        ),
    ]
