# Generated by Django 5.2 on 2025-04-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_rename_video_playlist_embed_historicalvendorprofile_playlist_embed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorprofile',
            name='playlist_embed',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendorprofile',
            name='video_embed',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='playlist_embed',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='video_embed',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
