# Generated by Django 5.2 on 2025-05-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_alter_historicalvendorprofile_playlist_embed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='bitcoin_cash_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='litecoin_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='tronix_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='trump_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='usdtether_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bitcoin_cash_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='litecoin_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tronix_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='trump_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='usdtether_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
