# Generated by Django 5.2.3 on 2025-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_rename_tronix_address_historicalvendorprofile_dogecoin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='logo_alpha',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='logo_alpha',
            field=models.FloatField(default=0.8),
        ),
    ]
