# Generated by Django 5.2.6 on 2025-10-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_historicalvendorprofile_logo_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='transistorfm_key',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='transistorfm_key',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
