# Generated by Django 5.2.8 on 2026-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_historicalvendorprofile_transistorfm_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='emergency_contact_1_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='emergency_contact_1_phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendorprofile',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='emergency_contact_1_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='emergency_contact_1_phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
