#!/bin/bash
OLDNAME='Lotte Harper'
NEWNAME=$1
OLDDOMAIN='lotteh.com'
NEWDOMAIN=$2
OLDHOST='lotteh'
NEWHOST=$3
OLDUSER='team'
NEWUSER=$6
OLDPROJ='lotteh'
NEWPROJ=$3
OLDSET='lotteh'
NEWSET=$3
OLDPREF='Lotte'
NEWPREF=$4
OLDEM='jasper.camber.holton@gmail.com'
NEWEM=$5
cd
cd $NEWPROJ
string0="s@${OLDDOMAIN}@${NEWDOMAIN}@g"
string1="s@${OLDHOST}@${NEWHOST}@g"
string2="s@${OLDUSER}@${NEWUSER}@g"
string3="s@${OLDPROJ}@${NEWPROJ}@g"
string4="s@${OLDNAME}@${NEWNAME}@g"
string5="s@${OLDSET}@${NEWSET}@g"
string6="s@${OLDPREF}@${NEWPREF}@g"
string7="s@${OLDEM}@${NEWEM}@g"
FILES="scripts/setup
scripts/initialize
scripts/convert
scripts/loadtables
scripts/dumptables
scripts/githubsetup
.github/workflows/django.yml
scripts/backup
scripts/activate
scripts/check
scripts/reload
scripts/daphnetest
$NEWPROJ/settings.py
config/$NEWPROJ-le-ssl.conf
config/crontab
config/etc_conf.d_celery
config/etc_default_celery
config/etc_default_celerybeat
config/etc_default_celeryd
config/etc_default_opendkim
config/etc_dovecot_conf.d_10-auth.conf
config/etc_dovecot_conf.d_10-master.conf
config/etc_dovecot_dovecot.conf
config/etc_dovecot_passwd
config/etc_init.d_celery
config/etc_init.d_celerybeat
config/etc_opendkim.conf
config/etc_pam.d_login
config/etc_pam.d_sshd
config/etc_postfix_main.cf
config/etc_postfix_master.cf
config/etc_systemd_system_celery.service
config/etc_systemd_system_celerybeat.service
config/etc_systemd_system_celeryd.service
config/etc_systemd_system_celeryd_beat.service
config/etc_systemd_system_daphne.service
config/etc_systemd_system_stun.service
config/rewrite.conf
config/ssh_config
config/sudoers
manage.py
process_recording.py
logout.py
login.py
unlock.py
force_id_valid.py
auth_code.py
crypto_trading.py
routine_enhance.py
routine_caption.py
admin.py
reload.py
pam.sh
pam.py
logout.sh
scripts/reload
$NEWPROJ/celery.py
$NEWPROJ/wsgi.py
$NEWPROJ/asgi.py
shell/templates/shell/edit.html
users/templates/users/password_reset_email.html
users/templates/users/password_reset_html_email.html"
while read p; do
	sudo sed -i "$string0" $"/usr/bin/$p"
	sudo sed -i "$string1" $"/usr/bin/$p"
	sudo sed -i "$string2" $"/usr/bin/$p"
	sudo sed -i "$string3" $"/usr/bin/$p"
	sudo sed -i "$string4" $"/usr/bin/$p"
	sudo sed -i "$string5" $"/usr/bin/$p"
	sudo sed -i "$string6" $"/usr/bin/$p"
done < config/ascripts
while read p; do
	sudo sed -i "$string0" $"scripts/$p"
	sudo sed -i "$string1" $"scripts/$p"
	sudo sed -i "$string2" $"scripts/$p"
	sudo sed -i "$string3" $"scripts/$p"
	sudo sed -i "$string4" $"scripts/$p"
	sudo sed -i "$string5" $"scripts/$p"
	sudo sed -i "$string6" $"scripts/$p"
done < config/ascripts
for f in $FILES; do
	sed -i "$string0" "$f"
	sed -i "$string1" "$f"
	sed -i "$string2" "$f"
	sed -i "$string3" "$f"
	sed -i "$string4" "$f"
	sed -i "$string5" "$f"
	sed -i "$string6" "$f"
done
for f in */*.py; do
	sed -i "$string3" "$f"
done
for f in *.py; do
	sed -i "$string3" "$f"
done
for f in *.py; do
	sed -i "$string5" "$f"
done
for f in */*/*.py; do
	sed -i "$string5" "$f"
done
for f in */*.html; do
	sed -i "$string5" "$f"
done
for f in */*/*/*.html; do
	sed -i "$string5" "$f"
done
for f in */*.txt; do
	sed -i "$string5" "$f"
done
for f in */*/*/*.txt; do
	sed -i "$string5" "$f"
done
echo "Replaced $OLDPROJ with $NEWPROJ"
