#!/bin/bash
DIR="/home/team/mupgirl"
USER="team"
sudo cp $DIR/config/ascripts /etc/ascripts
# Script setup
while read p; do
  sudo cp $DIR/scripts/$p /usr/bin/$p
  sudo chmod a+x /usr/bin/$p
done < /etc/ascripts
