#!/bin/bash
cd /home/team/lotteh
source venv/bin/activate
python manage.py makemigrations
python manage.py migrate --run-syncdb
./scripts/loadapp auth
./scripts/loadapp sessions
./scripts/loadapp address
python clear_empty_profiles_table.py
./scripts/loadapp users
./scripts/loadapp feed.post
./scripts/loadapp feed.bid
./scripts/loadapp chat
./scripts/loadapp verify
./scripts/loadapp security
./scripts/loadapp payments
./scripts/loadapp vendors
./scripts/loadapp barcode
./scripts/loadapp webauth
./scripts/loadapp voice
./scripts/loadapp tts
./scripts/loadapp games
./scripts/loadapp audio
./scripts/loadapp live
./scripts/loadapp translate
./scripts/loadapp contact
./scripts/loadapp payments
./scripts/loadapp chat
./scripts/loadapp survey
./scripts/loadapp crypto
./scripts/loadapp birthcontrol
./scripts/loadapp webpush
./scripts/loadapp translate
