#!/bin/bash
U="team"
DIR="lotteh"
GIT_URL=`sed -n '5p' < /home/$U/$DIR/config/git`
cd $"/home/$U/$DIR/"
sudo chown -R :users ./
sudo chmod -R 775 ./
source venv/bin/activate
if [ $# -eq 0 ]; then
	python generate_site.py
fi
cp -r static/games/ web/site/static/
sudo cp web/site/en/* web/site/
# Sub website backup
cd $"/home/$U/$DIR/web/site/"
#sudo rm -r .git
git config --global --add safe.directory /home/team/lotteh/web/site
sudo git config --global --add safe.directory $"/home/$U/$DIR/web/site/"
sudo git init --initial-branch=main
sudo git add --all
sudo git commit -m "website updates"
sudo git remote add origin $GIT_URL
sudo git push -u origin main
