#!/bin/bash
sudo apt remove --purge redis redis-server
sudo apt install -y redis
sudo chown -R redis:redis /var/lib/redis
sudo chown -R redis:redis /var/log/redis
sudo chmod -R u+rwX,g+rwX,u+rx /var/log/redis
sudo chmod +r /etc/redis/redis.conf
sudo systemctl restart redis
# Add redis config
sudo redis-cli config set stop-writes-on-bgsave-error no
sudo redis-cli config set appendonly no
sudo redis-cli config set save ""
# Fix redis perms
sudo chown -R redis:redis /var/lib/redis
sudo chown -R redis:redis /var/log/redis
sudo chmod -R u+rwX,g+rwX,u+rx /var/log/redis
sudo chmod +r /etc/redis/redis.conf
sudo systemctl restart redis
sudo systemctl start redis postgresql
