#!/bin/bash
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
