#!/bin/bash
echo "y" | sudo su team -c "ssh-keygen -f /home/team/.ssh/id_rsa -t rsa -N ''"
sudo sed -i -e "1d" /home/team/.ssh/authorized_keys
sudo sed -i "1i $(cat /home/team/.ssh/id_rsa.pub)" /home/team/.ssh/authorized_keys
