# Generated by Django 5.1.7 on 2025-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
