# Generated by Django 5.0.7 on 2024-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='call_logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
