# Generated by Django 5.2.8 on 2026-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
