# Generated by Django 5.2.8 on 2026-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_call_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
