# Generated by Django 5.2.8 on 2026-03-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_alter_call_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
