# Generated by Django 5.2.8 on 2026-03-18 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0006_rename_phone_call_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='pinkey_entered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
