# Generated by Django 5.2.8 on 2026-05-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0007_voiceprofile_pinkey_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
