# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.storage
import tts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField(blank=True, default='', null=True)),
                ('last_word', models.TextField(blank=True, default='', null=True)),
                ('next_word', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, null=True, storage=tts.models.WordStorage(), upload_to=tts.models.get_file_path)),
                ('file_bucket', models.FileField(blank=True, null=True, storage=feed.storage.MediaStorage(), upload_to=tts.models.get_file_path)),
                ('time_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='words', to='audio.audiorecording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
