# Generated by Django 5.0.6 on 2024-05-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_word_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='next_word_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
