# Generated by Django 5.0.1 on 2024-01-18 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0006_post_secure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
                ('begun', models.BooleanField(default=False)),
                ('turn', models.TextField(default='')),
                ('turns', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='feed.post')),
            ],
        ),
    ]
