# Generated by Django 5.2.3 on 2025-06-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='description',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
