# Generated by Django 5.2.3 on 2025-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_sharedlink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', null=True),
        ),
    ]
