# Generated by Django 5.2.8 on 2026-04-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='other',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
