# Generated by Django 5.2.6 on 2025-09-30 01:25

import backup.models
import django.utils.timezone
import lotteh.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBackup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, storage=lotteh.storages.BackupMediaStorage, upload_to=backup.models.get_file_path)),
            ],
        ),
    ]
