# Generated by Django 4.2.5 on 2023-10-04 16:02

import barcode.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.TextField(default='')),
                ('document', models.ImageField(blank=True, default=None, null=True, upload_to=barcode.models.get_document_path)),
                ('document_full', models.ImageField(blank=True, default=None, null=True, upload_to=barcode.models.get_document_path)),
                ('document_isolated', models.ImageField(blank=True, default=None, null=True, upload_to=barcode.models.get_document_path)),
                ('barcode_data', models.TextField(default='')),
                ('idscan', models.TextField(default='')),
                ('barcode_data_processed', models.TextField(default='')),
                ('side', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('foreign', models.BooleanField(default=False)),
                ('succeeded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
