# Generated by Django 5.0.7 on 2024-08-24 16:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumentScan',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.TextField(default='')),
                ('document', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('document_full', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('document_isolated', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('barcode_data', models.TextField(default='')),
                ('idscan', models.TextField(default='')),
                ('barcode_data_processed', models.TextField(default='')),
                ('side', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('foreign', models.BooleanField(default=False)),
                ('succeeded', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document scan',
                'verbose_name_plural': 'historical document scans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
