# Generated by Django 5.2.3 on 2025-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_historicaldocumentscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscan',
            name='subjective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocumentscan',
            name='subjective',
            field=models.BooleanField(default=False),
        ),
    ]
