# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(default='', max_length=20)),
                ('holding', models.BooleanField(default=False)),
                ('investment_amount_usd', models.FloatField(default=0)),
                ('holding_amount_usd', models.FloatField(default=0)),
                ('holding_amount', models.FloatField(default=0)),
                ('last_trade_price_not_holding', models.FloatField(default=0)),
                ('last_trade_price_holding', models.FloatField(default=0)),
                ('test_mode', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=10)),
                ('amount', models.FloatField(default=0)),
                ('amount_usd', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='crypto.bot')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTradingProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binance_api_key', models.TextField(default='')),
                ('binance_api_secret', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_trading_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
