# Generated by Django 5.0.7 on 2024-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rec',
            field=models.CharField(default='', max_length=20),
        ),
    ]
